
# source default xinitrc scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# remove beep
/usr/bin/setterm -blength 0
/usr/bin/xset b off

# remove screenblanking and energystar options
/usr/bin/xset -display :0 s off -dpms &

exec /usr/bin/startxfce4

